class Book{
    constructor(title, author, isbn) {
        this.title = title;
        this.author = author;
        this.isbn = isbn;
    }

}

class UI {
    addBookToList (book){
        const list = document.getElementById('book-list');

    //create tr

    const row = document.createElement('tr');

    // insert cols

    row.innerHTML = `
    <td>${book.title}</td>
    <td>${book.author}</td>
    <td>${book.isbn}</td>
    <td><a href= "#" class='delete'>X</a></td>
    `;

    list.appendChild(row);

    }

    showAlert (message, className){
        //create div
    
        const div = document.createElement('div');
        
        // add classes
    
        div.className = `alert ${className}`;

        // add text

        div.appendChild(document.createTextNode(message));

        // get parent

        const container = document.querySelector('.container');
        const form = document.querySelector('#book-form');

        // instert alert
        container.insertBefore(div, form);

        //time-out 

        setTimeout(function(){
            document.querySelector('.alert')
            .remove();
        }, 3000);

    }

    deleteBook (target){
        if(target.className === 'delete') {
            target.parentElement.parentElement.remove();
        }
    }

    clearFields (){
        document.getElementById('title').value = '';
        document.getElementById('author').value = '';
        document.getElementById('isbn').value = '';
    }
}

//Local storage class

class Store{

    static getBooks(){
        let book;
        if(localStorage.getItem('books') === null) {
            books = [];
        }else {
            books = JSON.parse( localStorage.getItem('books'));
        }

        return books;
    }

    static displayBooks(){
        const books = Store.getBooks();

        books.forEach(function(book) {
            const ui = new UI;

            ui.addBookToList(book);
            
        });
    }

    static addBook(){
        const books = Store.getBooks();

        books.push(book);

        localStorage.setItem('books', JSON.stringify(books));
    }

    static removeBook(isbn){
        const books = Store.getBooks();

        books.forEach(function(book) {
            if(book.isbn === isbn){
                books.splice(index, 1);
            }
        });

        localStorage.setItem('books', JSON.stringify(books));
    }

}



//DOM Load event

document.addEventListener('DOMContentLoaded', Store.displayBooks);




//event listeners

document.getElementById('book-form').addEventListener('submit' , 
function(e) {

    // get form values

    const title = document.getElementById('title').value,
          author = document.getElementById('author').value,
          isbn = document.getElementById('isbn').value

   // instatiating a book

    const book = new Book(title, author, isbn);

    // instantiat US

    const ui = new UI();

    //validate

    if(title === '' || author === '' || isbn === ''){
    // error alert
    ui.showAlert('Please fill in all fields', 'error');
    } else{
      
    //add book to list

    ui.addBookToList(book);

    // add book to local storage

    Store.addBook(book);

    //show success

    ui.showAlert('Book has been added!' , 'success');

    // clear fields

    ui.clearFields();
    }


    e.preventDefault();
});

// event listener for delete

document.getElementById('book-list').addEventListener('click' , function(e){
    //instantiate ui
    
    const ui = new UI ();

    // delete book

    ui.deleteBook(e.target);

    //remove from Local storage

    Store.removeBook(e.target.parentElement.previousElementSibling.textContent);

    //show message

    ui.showAlert('Book deleted!', 'success');
    
    e.preventDefault();
});